# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines

steps:

- script: 'python3 -m pip install --upgrade pip'
  displayName: 'Install pip'

- script: |
   pip3 install PyYAML
   
  displayName: 'Install Yaml'
  
- task: PythonScript@0
  displayName: 'Run a Python script'
  inputs:
    scriptPath: main.py

- script: |
   git config --global user.email "sattri@digitalocean.com"
   git config --global user.name "R4sammy"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Config Git' 

- script: |
   git -v
   git config --list
   git checkout -b main
   git add -A
   git commit -m "deployment $(Build.BuildNumber)"
   git remote set-url --add origin https://R4sammy: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@github.com/attri-sagar/attack_demo.git
   git push --set-upstream origin main
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Update file back to Repo'
