# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines

steps:

- checkout: self
  persistCredentials: true

- script: 'python3 -m pip install --upgrade pip'
  displayName: 'Install pip'

- script: |
   pip3 install PyYAML
   
  displayName: 'Install Yaml'
  
- task: PythonScript@0
  displayName: 'Run a Python script'
  inputs:
    scriptPath: main.py

- script: |
   git config --global user.email "sattri@digitalocean.com"
   git config --global user.name "R4sammy"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Config Git' 

- script: |
   git checkout -b main
   git add -A
   git commit -m "deployment $(Build.BuildNumber)"
   git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Update file back to Repo'
